### ISSUE TITLE
mochiweb and mochiweb_html causing release issues.

### ISSUE THREAD

**Issue by aphillipo** [mochi/mochiweb#181]
Firstly thanks loads for mochiweb - it's incredible and simple at the same time.

Now I have an issue where two packages are using mochiweb for html parsing but one uses mochiweb_html (floki) and the other uses mochiweb (phoenix_html_sanetizer).  This causes a release to break because it needs to have only one of the sub packages included but it thinks they are all included twice.

If there is a way to avoid this (override the subpackages?) I'd love to know!  I'm not really certain why mochiweb_html exists...

**Comment by etrepum** [comment]
No idea, that's more of a problem with those other packages and their namespace clash and how Erlang works. It's not a problem with mochiweb itself.

mochiweb_html exists because we needed it for scraping at the time, and in the bad old days it was far easier and more efficient to have a small number of dependencies so most of our open source ended in this one package. Never got split up.

**Comment by aphillipo** [comment]
No definitely not a problem with Mochiweb - I've contacted the authors of the relevant packages to see if they can depend on just :mochiweb - let's see!  Sorry for involving you in this as I wasn't sure where the problem was earlier.
